# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainform(object):
    def setupUi(self, mainform):
        mainform.setObjectName("mainform")
        mainform.resize(887, 626)
        mainform.setAutoFillBackground(False)
        self.horizontalLayoutWidget = QtWidgets.QWidget(mainform)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 540, 721, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_NewMessage = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_NewMessage.sizePolicy().hasHeightForWidth())
        self.pushButton_NewMessage.setSizePolicy(sizePolicy)
        self.pushButton_NewMessage.setObjectName("pushButton_NewMessage")
        self.horizontalLayout.addWidget(self.pushButton_NewMessage)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_DeleteMessage = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DeleteMessage.sizePolicy().hasHeightForWidth())
        self.pushButton_DeleteMessage.setSizePolicy(sizePolicy)
        self.pushButton_DeleteMessage.setObjectName("pushButton_DeleteMessage")
        self.horizontalLayout.addWidget(self.pushButton_DeleteMessage)
        self.pushButton_LoginWechat = QtWidgets.QPushButton(mainform)
        self.pushButton_LoginWechat.setGeometry(QtCore.QRect(60, 10, 61, 21))
        self.pushButton_LoginWechat.setObjectName("pushButton_LoginWechat")
        self.label_2 = QtWidgets.QLabel(mainform)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 76, 31))
        self.label_2.setObjectName("label_2")
        self.label_username = QtWidgets.QLabel(mainform)
        self.label_username.setGeometry(QtCore.QRect(140, 51, 211, 31))
        self.label_username.setText("")
        self.label_username.setObjectName("label_username")
        self.tableWidget_MSG = QtWidgets.QTableWidget(mainform)
        self.tableWidget_MSG.setGeometry(QtCore.QRect(60, 160, 721, 371))
        self.tableWidget_MSG.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_MSG.setShowGrid(False)
        self.tableWidget_MSG.setRowCount(10)
        self.tableWidget_MSG.setObjectName("tableWidget_MSG")
        self.tableWidget_MSG.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_MSG.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_MSG.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_MSG.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_MSG.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_MSG.setHorizontalHeaderItem(4, item)
        self.tableWidget_MSG.verticalHeader().setVisible(False)
        self.tableWidget_MSG.verticalHeader().setHighlightSections(True)

        self.retranslateUi(mainform)
        QtCore.QMetaObject.connectSlotsByName(mainform)

    def retranslateUi(self, mainform):
        _translate = QtCore.QCoreApplication.translate
        mainform.setWindowTitle(_translate("mainform", "微信伴侣"))
        self.pushButton_NewMessage.setText(_translate("mainform", "新建消息"))
        self.pushButton.setText(_translate("mainform", "预览消息"))
        self.pushButton_DeleteMessage.setText(_translate("mainform", "删除消息"))
        self.pushButton_LoginWechat.setText(_translate("mainform", "登录微信"))
        self.label_2.setText(_translate("mainform", "微信用户名:"))
        item = self.tableWidget_MSG.horizontalHeaderItem(0)
        item.setText(_translate("mainform", "消息序号"))
        item = self.tableWidget_MSG.horizontalHeaderItem(1)
        item.setText(_translate("mainform", "发送时间"))
        item = self.tableWidget_MSG.horizontalHeaderItem(2)
        item.setText(_translate("mainform", "发送对象"))
        item = self.tableWidget_MSG.horizontalHeaderItem(3)
        item.setText(_translate("mainform", "重复类型"))
        item = self.tableWidget_MSG.horizontalHeaderItem(4)
        item.setText(_translate("mainform", "发送内容"))

