# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messagebox.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_messagebox(object):
    def setupUi(self, messagebox):
        messagebox.setObjectName("messagebox")
        messagebox.resize(741, 474)
        messagebox.setAutoFillBackground(False)
        self.horizontalLayoutWidget = QtWidgets.QWidget(messagebox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 160, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_Repeat = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Repeat.setObjectName("label_Repeat")
        self.horizontalLayout.addWidget(self.label_Repeat)
        self.comboBox_Repeat = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_Repeat.setMouseTracking(False)
        self.comboBox_Repeat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_Repeat.setObjectName("comboBox_Repeat")
        self.comboBox_Repeat.addItem("")
        self.comboBox_Repeat.addItem("")
        self.comboBox_Repeat.addItem("")
        self.comboBox_Repeat.addItem("")
        self.comboBox_Repeat.addItem("")
        self.comboBox_Repeat.addItem("")
        self.comboBox_Repeat.addItem("")
        self.comboBox_Repeat.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_Repeat)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(messagebox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 60, 160, 22))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_Sendtime = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_Sendtime.setObjectName("label_Sendtime")
        self.horizontalLayout_2.addWidget(self.label_Sendtime)
        self.timeEdit_Sendtime = QtWidgets.QTimeEdit(self.horizontalLayoutWidget_2)
        self.timeEdit_Sendtime.setObjectName("timeEdit_Sendtime")
        self.horizontalLayout_2.addWidget(self.timeEdit_Sendtime)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(messagebox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 100, 160, 21))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Msgcontent = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_Msgcontent.setObjectName("label_Msgcontent")
        self.horizontalLayout_3.addWidget(self.label_Msgcontent)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(messagebox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(40, 140, 261, 22))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_city = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_city.sizePolicy().hasHeightForWidth())
        self.checkBox_city.setSizePolicy(sizePolicy)
        self.checkBox_city.setText("")
        self.checkBox_city.setObjectName("checkBox_city")
        self.horizontalLayout_4.addWidget(self.checkBox_city)
        self.label_Weather = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Weather.sizePolicy().hasHeightForWidth())
        self.label_Weather.setSizePolicy(sizePolicy)
        self.label_Weather.setObjectName("label_Weather")
        self.horizontalLayout_4.addWidget(self.label_Weather)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lineEdit_Weather = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Weather.sizePolicy().hasHeightForWidth())
        self.lineEdit_Weather.setSizePolicy(sizePolicy)
        self.lineEdit_Weather.setMaximumSize(QtCore.QSize(120, 100))
        self.lineEdit_Weather.setText("")
        self.lineEdit_Weather.setFrame(True)
        self.lineEdit_Weather.setDragEnabled(False)
        self.lineEdit_Weather.setClearButtonEnabled(True)
        self.lineEdit_Weather.setObjectName("lineEdit_Weather")
        self.horizontalLayout_4.addWidget(self.lineEdit_Weather)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(messagebox)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(40, 220, 261, 22))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_meiri = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_meiri.sizePolicy().hasHeightForWidth())
        self.checkBox_meiri.setSizePolicy(sizePolicy)
        self.checkBox_meiri.setText("")
        self.checkBox_meiri.setObjectName("checkBox_meiri")
        self.horizontalLayout_5.addWidget(self.checkBox_meiri)
        self.label_Daily = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Daily.sizePolicy().hasHeightForWidth())
        self.label_Daily.setSizePolicy(sizePolicy)
        self.label_Daily.setObjectName("label_Daily")
        self.horizontalLayout_5.addWidget(self.label_Daily)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.comboBox_Daily = QtWidgets.QComboBox(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Daily.sizePolicy().hasHeightForWidth())
        self.comboBox_Daily.setSizePolicy(sizePolicy)
        self.comboBox_Daily.setMaximumSize(QtCore.QSize(120, 100))
        self.comboBox_Daily.setObjectName("comboBox_Daily")
        self.comboBox_Daily.addItem("")
        self.comboBox_Daily.addItem("")
        self.comboBox_Daily.addItem("")
        self.comboBox_Daily.addItem("")
        self.comboBox_Daily.addItem("")
        self.comboBox_Daily.addItem("")
        self.comboBox_Daily.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_Daily)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(messagebox)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(40, 180, 261, 22))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_xingzuo = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_xingzuo.sizePolicy().hasHeightForWidth())
        self.checkBox_xingzuo.setSizePolicy(sizePolicy)
        self.checkBox_xingzuo.setText("")
        self.checkBox_xingzuo.setObjectName("checkBox_xingzuo")
        self.horizontalLayout_6.addWidget(self.checkBox_xingzuo)
        self.label_Constellation = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Constellation.sizePolicy().hasHeightForWidth())
        self.label_Constellation.setSizePolicy(sizePolicy)
        self.label_Constellation.setObjectName("label_Constellation")
        self.horizontalLayout_6.addWidget(self.label_Constellation)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.comboBox_Constellation = QtWidgets.QComboBox(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Constellation.sizePolicy().hasHeightForWidth())
        self.comboBox_Constellation.setSizePolicy(sizePolicy)
        self.comboBox_Constellation.setMaximumSize(QtCore.QSize(120, 100))
        self.comboBox_Constellation.setObjectName("comboBox_Constellation")
        self.comboBox_Constellation.addItem("")
        self.comboBox_Constellation.addItem("")
        self.comboBox_Constellation.addItem("")
        self.comboBox_Constellation.addItem("")
        self.comboBox_Constellation.addItem("")
        self.comboBox_Constellation.addItem("")
        self.comboBox_Constellation.addItem("")
        self.comboBox_Constellation.addItem("")
        self.comboBox_Constellation.addItem("")
        self.comboBox_Constellation.addItem("")
        self.comboBox_Constellation.addItem("")
        self.comboBox_Constellation.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_Constellation)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(messagebox)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(40, 260, 81, 22))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.checkBox_geren = QtWidgets.QCheckBox(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_geren.sizePolicy().hasHeightForWidth())
        self.checkBox_geren.setSizePolicy(sizePolicy)
        self.checkBox_geren.setSizeIncrement(QtCore.QSize(0, 0))
        self.checkBox_geren.setText("")
        self.checkBox_geren.setObjectName("checkBox_geren")
        self.horizontalLayout_7.addWidget(self.checkBox_geren)
        self.label_geren = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_geren.sizePolicy().hasHeightForWidth())
        self.label_geren.setSizePolicy(sizePolicy)
        self.label_geren.setObjectName("label_geren")
        self.horizontalLayout_7.addWidget(self.label_geren)
        self.textEdit_geren = QtWidgets.QTextEdit(messagebox)
        self.textEdit_geren.setGeometry(QtCore.QRect(130, 260, 171, 151))
        self.textEdit_geren.setObjectName("textEdit_geren")
        self.verticalLayoutWidget = QtWidgets.QWidget(messagebox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 430, 681, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_Preview = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Preview.setObjectName("pushButton_Preview")
        self.horizontalLayout_8.addWidget(self.pushButton_Preview)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.pushButton_Reset = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.horizontalLayout_8.addWidget(self.pushButton_Reset)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.pushButton_Determine = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Determine.setObjectName("pushButton_Determine")
        self.horizontalLayout_8.addWidget(self.pushButton_Determine)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.pushButton_Close = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.horizontalLayout_8.addWidget(self.pushButton_Close)
        self.label_8 = QtWidgets.QLabel(messagebox)
        self.label_8.setGeometry(QtCore.QRect(410, 30, 61, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(messagebox)
        self.label_9.setGeometry(QtCore.QRect(410, 200, 61, 20))
        self.label_9.setObjectName("label_9")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(messagebox)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(480, 30, 221, 22))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_9.addWidget(self.lineEdit_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.label_Repeat.setBuddy(self.comboBox_Repeat)
        self.label_Sendtime.setBuddy(self.timeEdit_Sendtime)

        self.retranslateUi(messagebox)
        self.pushButton_Close.clicked.connect(messagebox.close)
        QtCore.QMetaObject.connectSlotsByName(messagebox)

    def retranslateUi(self, messagebox):
        _translate = QtCore.QCoreApplication.translate
        messagebox.setWindowTitle(_translate("messagebox", "消息详情"))
        self.label_Repeat.setText(_translate("messagebox", "重复："))
        self.comboBox_Repeat.setToolTip(_translate("messagebox", "选择消息发送的频率"))
        self.comboBox_Repeat.setItemText(0, _translate("messagebox", "每天"))
        self.comboBox_Repeat.setItemText(1, _translate("messagebox", "星期一"))
        self.comboBox_Repeat.setItemText(2, _translate("messagebox", "星期二"))
        self.comboBox_Repeat.setItemText(3, _translate("messagebox", "星期三"))
        self.comboBox_Repeat.setItemText(4, _translate("messagebox", "星期四"))
        self.comboBox_Repeat.setItemText(5, _translate("messagebox", "星期五"))
        self.comboBox_Repeat.setItemText(6, _translate("messagebox", "星期六"))
        self.comboBox_Repeat.setItemText(7, _translate("messagebox", "星期日"))
        self.label_Sendtime.setText(_translate("messagebox", "时间："))
        self.timeEdit_Sendtime.setToolTip(_translate("messagebox", "设置消息发送的时间"))
        self.timeEdit_Sendtime.setStatusTip(_translate("messagebox", "设置消息发送的时间"))
        self.label_Msgcontent.setText(_translate("messagebox", "消息内容："))
        self.label_Weather.setText(_translate("messagebox", "天气预报"))
        self.lineEdit_Weather.setPlaceholderText(_translate("messagebox", "请输入城市名"))
        self.label_Daily.setText(_translate("messagebox", "每日一句"))
        self.comboBox_Daily.setToolTip(_translate("messagebox", "每日一句来源途径"))
        self.comboBox_Daily.setItemText(0, _translate("messagebox", "ONE ● 一个"))
        self.comboBox_Daily.setItemText(1, _translate("messagebox", "金山词霸 ● 每日一句"))
        self.comboBox_Daily.setItemText(2, _translate("messagebox", "一言 "))
        self.comboBox_Daily.setItemText(3, _translate("messagebox", "土味情话"))
        self.comboBox_Daily.setItemText(4, _translate("messagebox", "句子迷-民国情书"))
        self.comboBox_Daily.setItemText(5, _translate("messagebox", "随机获取笑话段子"))
        self.comboBox_Daily.setItemText(6, _translate("messagebox", "彩虹屁"))
        self.label_Constellation.setText(_translate("messagebox", "星座运势"))
        self.comboBox_Constellation.setToolTip(_translate("messagebox", "请选择获取运势的星座"))
        self.comboBox_Constellation.setItemText(0, _translate("messagebox", "水瓶座"))
        self.comboBox_Constellation.setItemText(1, _translate("messagebox", "双鱼座"))
        self.comboBox_Constellation.setItemText(2, _translate("messagebox", "白羊座"))
        self.comboBox_Constellation.setItemText(3, _translate("messagebox", "金牛座"))
        self.comboBox_Constellation.setItemText(4, _translate("messagebox", "双子座"))
        self.comboBox_Constellation.setItemText(5, _translate("messagebox", "巨蟹座"))
        self.comboBox_Constellation.setItemText(6, _translate("messagebox", "狮子座"))
        self.comboBox_Constellation.setItemText(7, _translate("messagebox", "处女座"))
        self.comboBox_Constellation.setItemText(8, _translate("messagebox", "天秤座"))
        self.comboBox_Constellation.setItemText(9, _translate("messagebox", "天蝎座"))
        self.comboBox_Constellation.setItemText(10, _translate("messagebox", "射手座"))
        self.comboBox_Constellation.setItemText(11, _translate("messagebox", "魔羯座"))
        self.label_geren.setText(_translate("messagebox", " 个人配置"))
        self.textEdit_geren.setPlaceholderText(_translate("messagebox", "请输入个人要发送的消息内容"))
        self.pushButton_Preview.setText(_translate("messagebox", "预览消息"))
        self.pushButton_Reset.setText(_translate("messagebox", "重置消息"))
        self.pushButton_Determine.setText(_translate("messagebox", "确定"))
        self.pushButton_Close.setText(_translate("messagebox", "关闭"))
        self.label_8.setText(_translate("messagebox", "好友名称："))
        self.label_9.setText(_translate("messagebox", "群聊名称："))
        self.label_10.setText(_translate("messagebox", "TextLabel"))


